---
title: "How Can We Prevent Gun Violence in Schools"
---

<style>
h1 {
  font-size: 36px; 
  font-weight: bold; 
  color: #333; 
  font-family: Times New Roman
}
h2 {
  font-size: 24px; 
  font-weight: bold; 
  color: #333; 
}
</style>

## Understanding the Crisis: The State of School Shootings
```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://cassiegoe.shinyapps.io/currentsit_app/"> </iframe>
```
On April 20, 1999, the deadliest high school shooting occurred at that time in the United States, sparking a national debate on gun control. The Columbine High School shooting in Colorado left 15 people dead and 21 wounded. This tragic event served as a catalyst for heightened awareness and scrutiny of gun violence in schools, setting the stage for ongoing efforts to address the issue. Fast forward to the present day, the alarming rise in the number of school shootings in the United States has reached unprecedented levels, underscoring the urgent need for effective strategies to prevent these tragic incidents. In 2022 alone, the nation witnessed a staggering 46 school shootings, marking the highest number of recorded incidents since 1999. This statistic paints a grim picture of the pervasive threat of gun violence in educational settings and its devastating impact on students, teachers, and communities across the country. 

According to the [Centers for Disease Control and Prevention (CDC)](https://www-cdc-gov.libproxy1.nus.edu.sg/violenceprevention/firearms/firearm-research-findings.html#:~:text=Taking%20into%20account%20all%20types,19%20in%202020%20and%202021.), gun-related injuries have emerged as the leading cause of death among children and teens in the US. However, beyond the physical injuries, these incidents also inflict long-lasting psychological trauma on students who have directly experienced a school shooting. The prevalence of anxiety and trauma stemming from the threat of school shootings has not only compromised the well-being of students but also disrupted their academic learning through increased absenteeism and decline in students’ academic performance following such incidents.

### View Details of Each School Shooting
```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://cassiegoe2.shinyapps.io/timeline_app/"> </iframe>
```

## Addressing the Epidemic: Factors
As we confront the alarming rise in school shootings, it becomes imperative to understand the factors driving this disturbing trend and to explore effective strategies for prevention. Merely acknowledging the grim reality of these incidents is not enough; we must also delve deeper into the root causes, systemic failures, and societal factors that contribute to the epidemic of school shootings. By examining these factors, we can identify areas for intervention and develop evidence-based solutions to prevent further tragedies. 

To address this issue, we can explore the following questions to gain a deeper insight:
- What are the common motivations and patterns observed among school shooters?
- What factors could have contributed to the rise in school shootings?
- How can understanding these factors help to prevent future occurrences?

### Location
```{=html}
<iframe height="700" width="100%" frameborder="no" src="https://cassiegoe2.shinyapps.io/choropleth_app/"> </iframe>
```

### School Environment 
```{=html}
<iframe height="600" width="100%" frameborder="no" src="https://cassiegoe.shinyapps.io/schoolenv_app/"> </iframe>
```

### Personal Motivations
```{=html}
<iframe height="700" width="100%" frameborder="no" src="https://cassiegoe2.shinyapps.io/personal_app/"> </iframe>
```

### Demographic Factors

#### Race
```{=html}
<iframe height="600" width="100%" frameborder="no" src="https://cassiegoe2.shinyapps.io/race_app/"> </iframe>
```

#### Age 
```{=html}
<iframe height="600" width="100%" frameborder="no" src="https://cassiegoe.shinyapps.io/age_app/"> </iframe>
```

### Access to Firearms
```{=html}
<iframe height="1000" width="100%" frameborder="no" src="https://cassiegoe.shinyapps.io/access_app/"> </iframe>
```

### Temporal Patterns 
```{=html}
<iframe height="1200" width="100%" frameborder="no" src="https://cassiegoe2.shinyapps.io/time_app/"> </iframe>
```

## Conclusion

